name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write  # Allows pushing release assets
      id-token: write  # Required for GitHub App authentication (if used)

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java (needed for Android builds)
      - name: Set up Java
      - uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk
            build/ios/iphoneos/app.ipa
          tag: v1.2.1
          generateReleaseNotes: false
          immutableCreate: false
          makeLatest: legacy
          omitBody: false
          omitBodyDuringUpdate: false
          omitDraftDuringUpdate: false
          omitName: false
          omitNameDuringUpdate: false
          omitPrereleaseDuringUpdate: false
          removeArtifacts: false
          replacesArtifacts: true
          skipIfReleaseExists: false
          updateOnlyUnreleased: false
          token: ${{ secrets.Project }}
        env:
          JAVA_HOME: /Users/runner/hostedtoolcache/Java_Zulu_jdk/17.0.16-8/arm64
          JAVA_HOME_17_ARM64: /Users/runner/hostedtoolcache/Java_Zulu_jdk/17.0.16-8/arm64
          FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.35.3-x64
          PUB_CACHE: /Users/runner/.pub-cache
